name: helm_simulator
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - gcc_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - gfortran_linux-64=11.2.0
  - cmake=3.21.3
  - make=4.3
  
  - python=3.12
  - pandas
  - numpy
  - scipy
  - matplotlib
  - plotly
  - deap
  - tqdm
  - notebook
  - memory_profiler
  - pip
  - pip:
    - sgp4==2.24
    - wmm2020==1.1.1
    - pyproj==3.6.1